version: "3.9"
services:

  gestion-station-ski:
    container_name: 5sae6-g2-gestion-station-ski
    image: "gestion-station-ski"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql-container
    volumes:
      - gestion-station-ski-data:/gestion-station-ski-data
    networks:
      - spring-network



  mysql-container:
    image: "mysql:5.6"
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysql_data:/opt/mysql/data
      - mysql_extenstions:/opt/mysql/extensions
      - mysql_logs:/mysql/logs
    networks:
      - spring-network

networks:
  spring-network:
volumes:
  gestion-station-ski-data:
  mysql_data:
  mysql_extenstions:
  mysql_logs:

