version: "3.9"
services:
  station-ski:
    image: station-ski
    container_name: station-ski
    ports:
      - "8089:8089"
    build: ../sae6_g2_skistation-
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/stationSki?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - db-mysql
    networks:
      - spring-network

  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - spring-network


networks:
  spring-network: