version: "3.9"
services:
  gestion-station-ski:
    build: ../sae6_g2_skistation-
    image: gestion-station-ski
    container_name: gestion-station-ski
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container-devops:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "8089:8089"
    depends_on:
      - mysql-container-devops
    networks:
      - devops-network


  mysql-container-devops:
    image: "mysql:5.6"
    container_name: mysql-container-devops
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - devops-network

networks:
  devops-network: